name: Jekyll Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.x'

      - name: Install Bundler and dependencies
        run: |
          bundle install

      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build --source . --destination ./_site